/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.ControladorCurso;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class VistaAltaCurso extends javax.swing.JFrame {
    protected JScrollPane jScrollPane1;
    protected Object[][] datos;
    public DefaultTableModel dtm;
    protected String[] cabecera;
    public JTable tabla;

    /**
     * Creates new form VistaAltaProfesor
     */
    public VistaAltaCurso() {
        jScrollPane1 = new JScrollPane();
        cabecera = new String[] {"Nombre", "Fecha In", "Fecha Ter", "Prof. Res", "Aula", "Hora Inicio", "Hora Fin", "Estado"};
        dtm = new DefaultTableModel(datos,cabecera);
        tabla = new JTable(dtm);
        jScrollPane1.setViewportView(tabla);
        
        initComponents();
        this.setVisible(true);
        this.setBounds(200, 200, 635, 415);
        
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 178, 600, 160);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAula = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        horaInicio = new javax.swing.JComboBox<>();
        minutoInicio = new javax.swing.JComboBox<>();
        horaFin = new javax.swing.JComboBox<>();
        minutoFin = new javax.swing.JComboBox<>();
        btnFechaInicio = new javax.swing.JButton();
        btnFechaFin = new javax.swing.JButton();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        profResponsable = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de un Curso");
        setPreferredSize(new java.awt.Dimension(585, 430));

        jLabel1.setText("Nombre:");

        jLabel4.setText("Profesor Responsable:");

        jLabel6.setText("Aula:");

        jLabel7.setText("Hora Inicio:");

        jLabel8.setText("Hora Fin:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        btnGuardar.setText("Guardar Cambios");

        btnRegresar.setText("Regresar");

        horaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));

        minutoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));

        horaFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));

        minutoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));

        btnFechaInicio.setText("Fecha Inicio:");
        btnFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaInicioActionPerformed(evt);
            }
        });

        btnFechaFin.setText("Fecha Temino:");

        profResponsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(minutoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFechaFin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFechaInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(profResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAula, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minutoFin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnGuardar)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnEliminar)
                .addGap(103, 103, 103)
                .addComponent(btnRegresar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFechaInicio)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFechaFin)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnAgregar)
                    .addComponent(horaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFechaInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAltaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAltaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAltaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAltaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAltaCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFechaFin;
    private javax.swing.JButton btnFechaInicio;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> horaFin;
    private javax.swing.JComboBox<String> horaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JComboBox<String> minutoFin;
    private javax.swing.JComboBox<String> minutoInicio;
    private javax.swing.JComboBox<String> profResponsable;
    private javax.swing.JTextField txtAula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    public void conectarControlador(ControladorCurso c) {
        //To change body of generated methods, choose Tools | Templates.
        btnRegresar.addActionListener((ActionListener) c);
        btnRegresar.setActionCommand("Regresar");
        
        btnFechaInicio.addActionListener((ActionListener) c);
        btnFechaInicio.addKeyListener((KeyListener) c);
        btnFechaInicio.setActionCommand("Fecha Inicio:");
        
        btnFechaFin.addActionListener((ActionListener) c);
        btnFechaFin.addKeyListener((KeyListener) c);
        btnFechaFin.setActionCommand("Fecha Termino:");
        
        btnAgregar.addActionListener((ActionListener) c);
        btnAgregar.setActionCommand("Agregar");
        
        btnEliminar.addActionListener((ActionListener) c);
        btnEliminar.setActionCommand("Eliminar");
        
        btnGuardar.addActionListener((ActionListener) c);
        btnGuardar.setActionCommand("Guardar");
        
        tabla.addMouseListener(c);
    }

    public void conectaControlador(ControladorCurso co) {
        //To change body of generated methods, choose Tools | Templates.
        btnRegresar.addActionListener((ActionListener) co);
        btnRegresar.setActionCommand("Regresar");
        
        btnFechaInicio.addActionListener((ActionListener) co);
        btnFechaInicio.setActionCommand("Fecha Inicio:");
        
        btnFechaFin.addActionListener((ActionListener) co);
        btnFechaFin.setActionCommand("Fecha Termino:");
        
        btnAgregar.addActionListener((ActionListener) co);
        btnAgregar.setActionCommand("Agregar");
        
        btnEliminar.addActionListener((ActionListener) co);
        btnEliminar.setActionCommand("Eliminar");
        
        btnGuardar.addActionListener((ActionListener) co);
        btnGuardar.setActionCommand("Guardar Cambios");
        
        tabla.addMouseListener(co);
    }
    
    public void setNombre(String n){
        txtNombre.setText(n);
    }
    
    public void setFechaInicio(String f){
        lblFechaInicio.setText(f);
    }
    
    public void setFechaFin(String f){
        lblFechaFin.setText(f);
    }
    
    public void setProfesorResponsable(String p){
        profResponsable.setSelectedItem(p);
    }
    
    public void setAula(String a){
        txtAula.setText(a);
    }
    
    public void setModelo(List<String> cursos){
        Vector aux = new Vector(0,1);
        for(int x = 0; x < cursos.size(); x++)
            aux.addElement(cursos.get(x));
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(aux);
        profResponsable.setModel(modelo);
    }
    
    public void setHoraInicio(String hora) {
        horaInicio.setSelectedItem(hora);
    }
    
    public void setHoraFin(String hora) {
        horaFin.setSelectedItem(hora);
    }
    
    public void setMinutoInicio(String min) {
        minutoInicio.setSelectedItem(min);
    }
    
    public void setMinutoFin(String min) {
        minutoFin.setSelectedItem(min);
    }
    //*********************************************************************************
    
    public JLabel getLIda()     {   return lblFechaInicio;                 }
    
    public JLabel getFechaF()     {   return lblFechaFin;                 }
    
    public String getNombre(){
        return txtNombre.getText();
    }
    
    public String getFechaInicio(){
        return lblFechaInicio.getText();
    }
    
    public String getFechaFin(){
        return lblFechaFin.getText();
    }
    
    public String getProfesorResponsable(){
        Object aux = profResponsable.getSelectedItem();
        return aux.toString();
    }
    
    public String getAula(){
        return txtAula.getText();
    }
    
    public String getHoraInicio(){
        Object aux = horaInicio.getSelectedItem();
        return aux.toString();
    }
    
    public String getHoraFin(){
        Object aux = horaFin.getSelectedItem();
        return aux.toString();
    }
    
    public String getMinutoInicio(){
        Object aux = minutoInicio.getSelectedItem();
        return aux.toString();
    }
    
    public String getMinutofin(){
        Object aux = minutoFin.getSelectedItem();
        return aux.toString();
    }
}
