/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.ControladorConsulta;
import java.awt.event.ActionListener;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class VistaConsulta extends javax.swing.JFrame {
        protected JScrollPane jScrollPane1;
        protected Object[][] datos;
        public DefaultTableModel dtm;
        protected String[] cabecera;
        public JTable tabla;
        
        protected JScrollPane jScrollPane11;
        protected Object[][] datos1;
        public DefaultTableModel dtm1;
        protected String[] cabecera1;
        public JTable tabla1;
    /**
     * Creates new form VistaConsultaCurso
     */
    public VistaConsulta() {
        initComponents();
        
        jScrollPane11 = new JScrollPane();
        cabecera1 = new String[] {"Nombre Curso", "Fecha Inicio", "Fecha Term", "Prof. Res", "Aula", "Hora Inicio", "Hora Fin", "Estado"};
        dtm1 = new DefaultTableModel(datos1,cabecera1);
        tabla1 = new JTable(dtm1);
        jScrollPane11.setViewportView(tabla1);
        getContentPane().add(jScrollPane11);
        jScrollPane11.setBounds(20, 30, 680, 50);
        
        jScrollPane1 = new JScrollPane();
        cabecera = new String[] {"ID","NOMBRE","AP PAT","AP MAT","CÉDULA", "ESTUDIO", "CARRERA", "CORREO"};
        dtm = new DefaultTableModel(datos,cabecera);
        tabla = new JTable(dtm);
        jScrollPane1.setViewportView(tabla);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 680, 200); //100,6802,200
        
        this.setLocation(200, 200);
        this.setTitle("Sistema de gestión de aprendizaje online");
        this.setVisible(true);
    }
    
    public static void main (String[] args){
        VistaConsulta v = new VistaConsulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATOS DEL CURSO");

        jLabel2.setText("PROFESORES INSCRITOS");

        btnAceptar.setText("ACEPTAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel2)))
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaConsulta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables


    public void conectaControlador(ControladorConsulta co) {  //To change body of generated methods, choose Tools | Templates.
        btnAceptar.addActionListener((ActionListener) co);
        btnAceptar.setActionCommand("ACEPTAR");
    }
}
